# -*- coding: utf-8 -*-
"""Untitled90.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FMtGTcuui2_wqQPFoBFysJHWynguHiB9

# **Saudi Stock Market Data Preparation Pipeline**
***Risk-Adjusted Sector Analysis Framework (2020–2026)***

This script serves as the primary data preparation workflow for the Saudi stock market sector analysis project.
Its purpose is to transform raw historical trading data into a validated, structured, and analysis-ready dataset
while preserving full compatibility with the Tableau dashboard layer.

**The pipeline follows a disciplined and reproducible approach that includes:**

1. Data Loading and Structural Inspection  
2. Data Type Standardization  
3. Core Data Cleaning (Missing Values & Duplicates)  
4. Logical Price Validation  
5. Exploratory Sanity Checks  
6. Feature Engineering (Daily Returns & Time Components)  
7. Visual Validation (Pre-Export Analysis Only)  
8. Final Structuring and Export  

The objective of this workflow is not to alter the business structure of the data, but to ensure logical integrity,
statistical reliability, and analytical readiness before visualization and sector-level modeling.


This exported dataset acts as the single source of truth for dashboard construction and sector performance evaluation.

# **1. Data Loading**


The first step is to load the raw dataset into the environment.
At this stage, no transformations are applied. The goal is simply to read the file and confirm that the dataset has been imported correctly before moving to cleaning or validation.
"""

import pandas as pd

# Load raw dataset from Colab directory
df = pd.read_csv("/content/historical_data.csv")

# Basic structural inspection
print("Initial shape:", df.shape)
print("Columns:", df.columns.tolist())
print("\nFirst 5 rows:")
print(df.head())

"""# **2. Data Type Standardization**
After loading the dataset, the next step is to ensure that all columns have the correct data types.
The date column must be converted into a proper datetime format so it can be used for time-based analysis.
Price and volume columns must be converted to numeric values to prevent calculation errors later when computing returns and volatility.
This step does not change the structure of the dataset it only ensures type consistency.
"""

df['date'] = pd.to_datetime(df['date'], errors='coerce')

numeric_cols = ['open','high','low','close','volume']
df[numeric_cols] = df[numeric_cols].apply(pd.to_numeric, errors='coerce')

"""# **3. Data Cleaning  Missing Values & Duplicates**
At this stage, the dataset is cleaned from structurally invalid records.
Only critical columns are considered when removing missing values, specifically those required for price calculations and sector-level analysis. Rows missing essential fields such as date, prices, volume, or sector are removed to ensure analytical integrity.
Duplicate rows are also eliminated to prevent distortion in aggregation, return calculations, or sector-level metrics.
This step ensures the dataset remains reliable while preserving its overall structure.
"""

df = df.dropna(subset=['date','open','high','low','close','volume','sector'])

df = df.drop_duplicates()

print("Shape after cleaning:", df.shape)

"""# **4. Logical Price Validation**
After removing missing values and duplicates, the dataset undergoes logical validation to ensure price consistency. Financial market data must follow realistic trading behavior, meaning that the recorded low price should not exceed the open or close, and the high price should not fall below them. Additionally, negative price or volume values are not valid in this context. Any rows violating these logical conditions are removed to preserve the integrity of return calculations and volatility analysis while keeping the overall dataset structure unchanged.
"""

# Logical price validation
price_logic_issues = df[
    (df['low'] > df['open']) |
    (df['low'] > df['close']) |
    (df['high'] < df['open']) |
    (df['high'] < df['close'])
]

print("Price logic issues:", len(price_logic_issues))

df = df.drop(price_logic_issues.index)

# Negative value validation
negative_values = df[
    (df['open'] < 0) |
    (df['high'] < 0) |
    (df['low'] < 0) |
    (df['close'] < 0) |
    (df['volume'] < 0)
]

print("Negative value issues:", len(negative_values))

df = df.drop(negative_values.index)

print("Shape after logical validation:", df.shape)

"""# **5. Exploratory Data Review**
Before moving into feature engineering, a brief exploratory review is performed to validate overall dataset consistency. This step confirms the date range coverage, sector distribution, and general price behavior. The purpose here is not transformation, but reassurance that the cleaned dataset reflects realistic market structure and sufficient sector representation for reliable comparative analysis.
"""

print("\nDate Range:")
print("Start:", df['date'].min())
print("End:", df['date'].max())

print("\nSector Distribution:")
print(df['sector'].value_counts())

print("\nPrice Summary Statistics:")
print(df[['open','high','low','close','volume']].describe())

"""# **6. Feature Engineering  Daily Return & Time Components**

With the dataset validated, derived features are created to support performance and volatility analysis. Daily return is calculated for each ticker using percentage change in closing prices. The data is first sorted to ensure chronological consistency within each ticker. Additionally, year, month, and quarter fields are extracted from the date column to enable time-based aggregation in the dashboard. These additions do not alter the dataset structure required by Tableau but enhance analytical flexibility.
"""

df = df.sort_values(['ticker','date'])

df['daily_return'] = (
    df.groupby('ticker')['close']
    .pct_change()
    .fillna(0)
)

df['year'] = df['date'].dt.year
df['month'] = df['date'].dt.month
df['quarter'] = df['date'].dt.quarter

print("Shape after feature engineering:", df.shape)
print("\nDaily Return Summary:")
print(df['daily_return'].describe())

"""# **6.5 Visual Validation (Pre-Export Analysis Only)**

Before exporting the final dataset, a preliminary visual validation step is conducted to ensure that return distributions and sector-level dispersion behave as expected. These visualizations are used strictly for internal analytical verification and do not alter the dataset structure or exported schema. Their purpose is to confirm statistical stability and detect any abnormal distortions prior to dashboard integration.

**Daily Return Distribution**

This visualization confirms that daily returns follow a reasonable distribution pattern and do not exhibit extreme structural anomalies.
"""

import matplotlib.pyplot as plt
import numpy as np

plt.figure()

plt.hist(
    df['daily_return'],
    bins=100,
    color="#0B6E4F",
    edgecolor="#2E8B57"
)

plt.title("Distribution of Daily Returns")
plt.xlabel("Daily Return")
plt.ylabel("Frequency")

plt.grid(alpha=0.2)
plt.show()

"""# Sector Volatility Comparison

This chart validates dispersion differences across sectors and confirms that no single sector exhibits unrealistic volatility spikes.
"""

sector_volatility = df.groupby('sector')['daily_return'].std().sort_values()

plt.figure()

sector_volatility.plot(
    kind='bar',
    color="#1F8A70"
)

plt.title("Sector-Level Volatility")
plt.ylabel("Standard Deviation of Daily Returns")
plt.xticks(rotation=45)

plt.grid(axis='y', alpha=0.2)
plt.show()

"""**Risk vs Return Scatter (Preliminary Check)**

This scatterplot provides a quick sanity check of return-risk positioning before final dashboard modeling.
"""

sector_stats = df.groupby('sector')['daily_return'].agg(['mean','std'])

plt.figure()

plt.scatter(
    sector_stats['std'],
    sector_stats['mean'],
    color="#145A32"   # Deep green
)

for i, sector in enumerate(sector_stats.index):
    plt.text(
        sector_stats['std'][i],
        sector_stats['mean'][i],
        sector,
        fontsize=8
    )

plt.xlabel("Volatility")
plt.ylabel("Average Daily Return")
plt.title("Preliminary Risk vs Return Positioning")

plt.grid(alpha=0.2)
plt.show()

"""These visual checks are conducted solely for internal validation prior to dataset export. They do not introduce structural changes, additional features, or modifications to the final Tableau-ready dataset.

# **7. Final Structuring & Export**

After completing data validation, feature engineering, and preliminary visual checks, the dataset is finalized for dashboard integration. At this stage, the column structure is explicitly reordered to match the schema expected by the Tableau dashboard. No additional fields are introduced, and no structural modifications are made beyond formatting. The cleaned and engineered dataset is then exported as a production-ready CSV file for visualization and sector-level analysis.
"""

df = df[['date','year','quarter','month',
         'ticker','company','sector',
         'open','high','low','close',
         'volume','daily_return']]

df.to_csv("/content/saudi_market_prepared.csv", index=False)

print("\nFinal shape:", df.shape)
print("\nMissing values check:\n", df.isnull().sum())

assert df.isnull().sum().sum() == 0, "Dataset still contains missing values"